apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kabanero-codewind-tekton-role
  namespace: tekton-pipelines
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
