kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kabanero-codewind-tekton
  namespace: tekton-pipelines
subjects:
- kind: ServiceAccount
  name: che-workspace
  namespace: kabanero
roleRef:
  kind: Role
  name: kabanero-codewind-tekton-role 
  apiGroup: rbac.authorization.k8s.io
