apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook.operator.kabanero.io
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: {{ .caBundle }}
    service:
      name: kabanero-operator-admission-webhook
      namespace: kabanero
      path: /mutate-collections
  failurePolicy: Fail
  name: mutating.collection.kabanero.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
  rules:
  - apiGroups:
    - kabanero.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - collections
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: {{ .caBundle }}
    service:
      name: kabanero-operator-admission-webhook
      namespace: kabanero
      path: /mutate-stacks
  failurePolicy: Fail
  name: mutating.stack.kabanero.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
  rules:
  - apiGroups:
    - kabanero.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - stacks
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30  
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: {{ .caBundle }}
    service:
      name: kabanero-operator-admission-webhook
      namespace: kabanero
      path: /mutate-kabaneros
  failurePolicy: Fail
  name: mutating.kabanero.kabanero.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
  rules:
  - apiGroups:
    - kabanero.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kabaneros
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook.operator.kabanero.io
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: {{ .caBundle }}
    service:
      name: kabanero-operator-admission-webhook
      namespace: kabanero
      path: /validate-collections
  failurePolicy: Fail
  name: validating.collection.kabanero.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
  rules:
  - apiGroups:
    - kabanero.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - collections
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: {{ .caBundle }}
    service:
      name: kabanero-operator-admission-webhook
      namespace: kabanero
      path: /validate-kabaneros
  failurePolicy: Fail
  name: validating.kabanero.kabanero.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
  rules:
  - apiGroups:
    - kabanero.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kabaneros
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: {{ .caBundle }}
    service:
      name: kabanero-operator-admission-webhook
      namespace: kabanero
      path: /validate-kabaneros/v1alpha2
  failurePolicy: Fail
  name: validating.kabanero.kabanero.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
  rules:
  - apiGroups:
    - kabanero.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - kabaneros
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: {{ .caBundle }}
    service:
      name: kabanero-operator-admission-webhook
      namespace: kabanero
      path: /validate-stacks
  failurePolicy: Fail
  name: validating.stack.kabanero.io
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
  rules:
  - apiGroups:
    - kabanero.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - stacks
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
