channels:
- currentCSV: openshift-pipelines-operator.v0.7.0
  name: kabanero-0.3
- currentCSV: openshift-pipelines-operator.v0.7.0
  name: kabanero-0.4
- currentCSV: openshift-pipelines-operator.v0.8.1
  name: kabanero-0.5
- currentCSV: openshift-pipelines-operator.v0.10.4
  name: kabanero-0.6
- currentCSV: openshift-pipelines-operator.v0.10.8
  name: kabanero-0.8
defaultChannel: kabanero-0.8
packageName: openshift-pipelines-operator
