apiVersion: v1
kind: Service
metadata:
  name: kabanero-operator-collection-controller
  labels:
    app.kubernetes.io/name: kabanero-operator-collection-controller
    app.kubernetes.io/instance: {{ .instance }}
    app.kubernetes.io/version: {{ .version }}
    app.kubernetes.io/component: collection-controller
    app.kubernetes.io/part-of: kabanero
    app.kubernetes.io/managed-by: kabanero-operator
spec:
  selector:
    app: kabanero-operator-collection-controller
  ports:
  - protocol: TCP
    port: 443
    targetPort: 9443
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: kabanero-operator-collection-controller
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - collection-operator
  verbs:
  - "update"
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - tekton.dev
  resources:
  - pipelines
  - tasks
  - triggerbindings
  - triggertemplates
  verbs:
  - delete
  - get
  - create
  - list
  - update
  - watch
- apiGroups:
  - kabanero.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kabanero-operator-collection-controller
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kabanero-operator-collection-controller
subjects:
- kind: ServiceAccount
  name: kabanero-operator-collection-controller
roleRef:
  kind: Role
  name: kabanero-operator-collection-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kabanero-operator-collection-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kabanero-operator-collection-controller
  template:
    metadata:
      labels:
        app: kabanero-operator-collection-controller
        app.kubernetes.io/name: kabanero-operator-collection-controller
        app.kubernetes.io/instance: {{ .instance }}
        app.kubernetes.io/version: {{ .version }}
        app.kubernetes.io/component: collection-controller
        app.kubernetes.io/part-of: kabanero
        app.kubernetes.io/managed-by: kabanero-operator
    spec:
      serviceAccountName: kabanero-operator-collection-controller
      containers:
        - name: kabanero-operator-collection-controller
          image: {{ .image }}
          imagePullPolicy: Always
          command:
          - /usr/local/bin/kabanero-operator-collection-controller
          env:
            - name: KABANERO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
