apiVersion: v1
kind: Service
metadata:
  name: kabanero-cli
spec:
  selector:
    app: kabanero-cli
  ports:
  - protocol: TCP
    port: 443
    targetPort: 9443
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kabanero-cli
spec:
  to:
    kind: Service
    name: kabanero-cli
  tls:
    termination: passthrough
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: kabanero-cli
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - get
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - kabanero-cli
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - kabanero.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kabanero-cli
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kabanero-cli
subjects:
- kind: ServiceAccount
  name: kabanero-cli
roleRef:
  kind: Role
  name: kabanero-cli
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kabanero-cli
rules:
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - route.openshift.io
  resources:
  - routes
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kabanero-cli
subjects:
- kind: ServiceAccount
  name: kabanero-cli
  namespace: kabanero
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kabanero-cli
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kabanero-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kabanero-cli
  template:
    metadata:
      labels:
        app: kabanero-cli
        app.kubernetes.io/name: kabanero-cli
        app.kubernetes.io/instance: {{ .instance }}
        app.kubernetes.io/version: {{ .version }}
        app.kubernetes.io/component: kabanero-cli
        app.kubernetes.io/part-of: kabanero
        app.kubernetes.io/managed-by: kabanero-operator
    spec:
      containers:
        - name: kabanero-cli
          livenessProbe:
            httpGet:
              path: /v1/liveliness
              port: 9443
              scheme: HTTPS
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: AESEncryptionKey
              valueFrom:
                secretKeyRef:
                  name: kabanero-cli-aes-encryption-key-secret
                  key: AESEncryptionKey
                  optional: false
            - name: KABANERO_CLI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 9443
              protocol: TCP
          imagePullPolicy: Always
          image: {{ .image }}
      serviceAccountName: kabanero-cli
