apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero
spec:
  version: "0.7.0"
  stacks:
    repositories:
    - name: central
      https:
        url: https://github.com/kabanero-io/kabanero-stack-hub/releases/download/0.7.0-rc.1/kabanero-stack-hub-index.yaml
    pipelines:
    - id: default
      sha256: 8d2cba24eef31fea470abc860909b407f0af54016acb79b723c04c711350d344
      https:
        url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.7.0-rc.1/default-kabanero-pipelines.tar.gz
