apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero
spec:
  version: "0.6.0"
  stacks: 
    repositories: 
    - name: central
      https:
        url: https://github.com/kabanero-io/collections/releases/download/0.6.0-rc.1/kabanero-index.yaml
    pipelines:
    - id: default
      sha256: f244c95ffbeca0554105a9b5a098ea8d0ffbed17cea39f43e078a86b62ff8984
      https:
        url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.6.0-rc3/default-kabanero-pipelines.tar.gz
