apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero
spec:
  version: "0.6.0"
  stacks: 
    repositories: 
    - name: central
      https:
        url: https://github.com/kabanero-io/collections/releases/download/0.6.0-rc.1/kabanero-index.yaml
    pipelines:
    - id: default
      sha256: c27921f25a30fdb4701762d6d1630e3192872ff4284b7731f4c223985bf62802
      https:
        url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.6.0-rc.5/default-kabanero-pipelines.tar.gz
