apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero1
spec:
  version: 0.1.0
  
  cliServices:
    # Overrides the internally determined CLI services version with the provided value
    version: "0.1.0"
---
apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero1
spec:
  cliServices:
    # Overrides the internally determined CLI services image with the provided value
    image: kabanero/kabanero-command-line-services:0.1.0
---
apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero2
spec:
  cliServices:
    # Overrides only the repository used by the CLI services.
    # The tag will be internally determined
    repository: kabanero/kabanero-command-line-services
---
apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero2
spec:
  cliServices:
    # Overrides only the tag used in the CLI services deployment
    # The repository will be internally determined
    tag: "0.1.1"
---
apiVersion: kabanero.io/v1alpha2
kind: Kabanero
metadata:
  name: kabanero3
spec:
  cliServices:
    # When both image and repository overrides are present, the image attribute
    # will take precedence
    image: kabanero/kabanero-command-line-services:0.1.0
    repository: kabanero/kabanero-command-line-services