# ServiceAccount, Role & RoleBinding for piplines to be run
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kabanero-pipeline
  namespace: {{ .pipelinesNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kabanero-pipeline-role
  namespace: {{ .pipelinesNamespace }}
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  - namespaces
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - watch
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - tasks
  - clustertasks
  - taskruns
  - pipelines
  - pipelineruns
  - pipelineresources
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - taskruns/finalizers
  - pipelineruns/finalizers
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - tasks/status
  - clustertasks/status
  - taskruns/status
  - pipelines/status
  - pipelineruns/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - kabanero.io
  resources:
  - stacks
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - ""
  - image.openshift.io
  resources:
  - imagestreams/layers
  verbs:
  - get
  - update
- apiGroups:
  - ""
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kabanero-pipeline-get-stack-role
  namespace: {{ .kabaneroNamespace }}
rules:
- apiGroups:
  - kabanero.io
  resources:
  - stacks
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kabanero-pipeline-role-binding
  namespace: {{ .pipelinesNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kabanero-pipeline-role
subjects:
- kind: ServiceAccount
  name: kabanero-pipeline
  namespace:  {{ .pipelinesNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kabanero-pipeline-get-stack-role-binding
  namespace: {{ .kabaneroNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kabanero-pipeline-get-stack-role
subjects:
- kind: ServiceAccount
  name: kabanero-pipeline
  namespace:  {{ .pipelinesNamespace }}
