apiVersion: v1
kind: Service
metadata:
  name: kabanero-landing
spec:
  selector:
    app: kabanero-landing
  ports:
  - protocol: TCP
    port: 443
    targetPort: 9443
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kabanero-landing
spec:
  to:
    kind: Service
    name: kabanero-landing
  tls:
    termination: passthrough
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kabanero-landing
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kabanero-landing
subjects:
- kind: ServiceAccount
  name: kabanero-landing
  namespace: kabanero
roleRef:
  kind: ClusterRole
  name: kabanero-landing
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kabanero-landing
  namespace: kabanero
rules:
- apiGroups:
  - ""
  - route.openshift.io
  attributeRestrictions: null
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - route.openshift.io
  attributeRestrictions: null
  resources:
  - routes/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kabanero.io
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
