kind: Deployment
apiVersion: apps/v1
metadata:
  name: kabanero-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kabanero-landing
  template:
    metadata:
      labels:
        app: kabanero-landing
        app.kubernetes.io/name: kabanero-landing
        app.kubernetes.io/instance: {{ .instance }}
        app.kubernetes.io/version: '0.1'
        app.kubernetes.io/component: kabanero-landing
        app.kubernetes.io/part-of: kabanero
        app.kubernetes.io/managed-by: kabanero-operator
    spec:
      containers:
        - name: kabanero-landing
          image: {{ .image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9443
              protocol: TCP
      serviceAccountName: kabanero-landing

